import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../../components/Header/Header'
import LowerHeader from '../../components/Header/LowerHeader'
import Slider from '../../components/Slider/Slider'
import Feed from '../../components/Feed/Feed'
import Widget from '../../components/Widget/Widget'
import FullHeader from '../../components/Header/FullHeader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <FullHeader />
      <main className='flex md:pt-16 pt-[160px]'>
        {/* Slider */}
        <Slider />
        {/* Feed */}
        <Feed />
        {/* Widget */}
        <Widget />
      </main>
    </>
  )
}
